# @package _global_
env:
  parallel_envs: 10

algorithm:
  _target_: decomp_ac.train.main
  name: "decomp_ac"

  model:
    _target_: decomp_ac.model.DecompA2CNetwork
    actor:
      layers:
        - 128
        - 128
      parameter_sharing: False
      use_orthogonal_init: True
      use_rnn: False
    critic:
      centralised: True        # True for Centralised Training (CTDE)
      layers:
        - 128
        - 128
      parameter_sharing: False  # False ensures N x M = 6 fully independent networks!
      use_orthogonal_init: True
      use_rnn: False

    device: "cuda"             # Set to "cpu" if running without a GPU

  n_reward_channels: 4
  coop_channel_idx: 2         # Channel 2 is ID_3 (Level 3 Coop Food)
  optimism_tau: 0.75          # > 0.5: Asymmetric leniency on coop critic loss
  channel_weights: [1.0, 1.0, 1.0, 1.0]
  use_adam_momentum: true    # true for Adam SNR routing; false for pure Polyak velocity
  momentum_beta1: 0.8        # 1st moment (0.7 to 0.85: higher means more commitment)
  momentum_beta2: 0.95       # 2nd moment (0.9 to 0.99: tracks noise volatility)

  optimizer: "Adam"
  lr: 3.e-4
  grad_clip: 0.5 # Changed from False
  n_steps: 5
  gamma: 0.99
  entropy_coef: 0.01 # changed from 0.001
  value_loss_coef: 0.5
  use_proper_termination: False
  standardise_returns: False # was: True
  target_update_interval_or_tau: 200

  total_steps: 1000000
  eval_interval: 20000
  save_interval: 0
  video_interval: 0
  video_frames: 200